# Generated by Django 4.0.6 on 2022-07-25 11:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dustbin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('capacity', models.FloatField()),
                ('max_height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recyclers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('recycles', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Weight_height',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_value', models.FloatField()),
                ('height_value', models.FloatField()),
                ('date', models.DateField()),
                ('dustbin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IOT.dustbin')),
            ],
        ),
        migrations.CreateModel(
            name='Recycles_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('kg', 'kilogram'), ('litre', 'litres'), ('lbs', 'pound'), ('gallon', 'Gallon')], max_length=255)),
                ('price_per_unit', models.FloatField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IOT.recyclers')),
            ],
        ),
    ]
