# Generated by Django 4.0.6 on 2022-07-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOT', '0002_rename_latitude_dustbin_latitude_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dustbin',
            name='location',
            field=models.CharField(default='Dhulikhel', max_length=255),
            preserve_default=False,
        ),
    ]
