# Generated by Django 4.0.6 on 2022-08-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOT', '0003_dustbin_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='dustbin',
            name='dustbin_type',
            field=models.CharField(choices=[('Paper', 'Paper'), ('Metal', 'Metal'), ('Plastics', 'Plastics'), ('Waste Food', 'Waste Food'), ('Bottles', 'Bottles')], default='Paper', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recyclers',
            name='recycles',
            field=models.CharField(choices=[('Paper', 'Paper'), ('Metal', 'Metal'), ('Plastics', 'Plastics'), ('Waste Food', 'Waste Food'), ('Bottles', 'Bottles')], max_length=255),
        ),
    ]
