# Generated by Django 4.0.6 on 2022-08-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOT', '0004_dustbin_dustbin_type_alter_recyclers_recycles'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclers',
            name='average_price',
            field=models.FloatField(default=13),
            preserve_default=False,
        ),
    ]
