# Generated by Django 4.0.6 on 2022-08-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOT', '0006_alter_weight_height_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dustbin',
            name='should_open',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
