# Generated by Django 4.0.6 on 2022-08-04 08:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('IOT', '0007_dustbin_should_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_to_auction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Paper', 'Paper'), ('Metal', 'Metal'), ('Plastics', 'Plastics'), ('Waste Food', 'Waste Food'), ('Bottles', 'Bottles')], max_length=255)),
                ('unit', models.CharField(choices=[('kg', 'kilogram'), ('litre', 'litres'), ('lbs', 'pound'), ('gallon', 'Gallon')], max_length=255)),
                ('total_no_of_units', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
