# Generated by Django 4.0.6 on 2022-08-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOT', '0008_item_to_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight_height',
            name='redeemed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item_to_auction',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('litres', 'litres'), ('pound', 'pound'), ('gallon', 'gallon')], max_length=255),
        ),
        migrations.AlterField(
            model_name='recycles_category',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('litres', 'litres'), ('pound', 'pound'), ('gallon', 'gallon')], max_length=255),
        ),
    ]
